package competition.network.rpcprotocol;

public enum  ResponseType {
    OK,
    ERROR,
//    GET_ATHLETIC_TEST_DTO,
//    GET_PARTICIPANTS_DTO,
//    GET_FIND_ALL_PARTICIPANTS_TEST_LEGTH_AND_AGE,
//    GET_ADD_PARTICIPANT_WITH_RETURNING,
//    GET_FIND_ATHLETIC_TEST_BY_TEST_LENGTH_AND_AGE,
    GET_UPDATE_PARTICIPANTS_DTO_ATHLETIC_TESTS_DTO
}
